spring:
  application:
    name: user-service
  profiles:
    group:
      local: local
      dev: dev, common
      prod: prod, common
      test: local
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8001/login/oauth2/code/google
  data:
    redis:
      host: localhost
      port: 6370
  servlet:
    multipart:
      max-file-size: 10MB
jwt:
  secret: ${JWT_SECRET}
  redirect: http://localhost:5173/oauth-callback?name=%s&access_token=%s
  access-token:
    expiration-time: 3600000
  refresh-token:
    expiration-time: 604800000

storage:
  path:
    profile: upload/files/profile/
---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:file:./build/data/user;MODE=PostgreSQL;AUTO_SERVER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    config:
      enabled: false
    bus:
      enabled: false
eureka:
  client:
    enabled: false
server:
  port: 8001
management:
  endpoints:
    web:
      exposure:
        include: none
  health:
    defaults:
      enabled: false
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
---

spring:
  config:
    activate:
      on-profile: common
server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: info, health, busrefresh

---

spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      uri: http://127.0.0.1:8888
      name: user
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---

spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      uri: http://config-server:8888
      name: user
  rabbitmq:
    host: rabbitmq-server
    port: 5672
    username: prod_user
    password: prod_password
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;
    username: sa
    password:
    driverClassName: org.h2.Driver
jwt:
  secret: forTestValue_1231231qweqwe
