spring:
  application:
    name: challenge-service
  profiles:
    group:
      local: local
      dev: dev, common
      prod: prod, common
      test: local

storage:
  path:
    challenge: upload/files/challenge/
---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    config:
      enabled: false
    bus:
      enabled: false
eureka:
  client:
    enabled: false
server:
  port: 8002
management:
  endpoints:
    web:
      exposure:
        include: none
  health:
    defaults:
      enabled: false

---

spring:
  config:
    activate:
      on-profile: common
server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: info, health, busrefresh

---

spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      uri: http://127.0.0.1:8888
      name: user
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---

spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      uri: http://config-server:8888
      name: user
  rabbitmq:
    host: rabbitmq-server
    port: 5672
    username: prod_user
    password: prod_password
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---

spring:
  config:
    activate:
      on-profile: test
